# @rharbach: absolutely unclear why this file is required. We are not even using the pilz planner (MoveItPy still needs it)
# Cartesian limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 1.0
  max_trans_acc: 2.25
  max_trans_dec: -5.0
  max_rot_vel: 1.57